# -*- coding: utf-8 -*-
from __future__ import annotations

from omron_io_planner.program_export import (
    cxr_text_from_ladder_networks,
    rows_variable_table,
    st_text_for_export,
)
from omron_io_planner.program_models import (
    FunctionBlock,
    LadderCell,
    LadderElement,
    LadderNetwork,
    ProgramUnit,
    StDocument,
    VariableDecl,
)


def test_rows_variable_table_exports_fb_variables_in_order() -> None:
    block = FunctionBlock(
        uid="fb-1",
        name="AxisHome",
        variables=[
            VariableDecl(name="Enable", data_type="BOOL", category="IN", comment="启动"),
            VariableDecl(name="Done", data_type="BOOL", category="OUT", comment="完成"),
        ],
    )

    rows = rows_variable_table(block.variables)

    assert rows == [
        ["类别", "名称", "数据类型", "注释", "初始值"],
        ["IN", "Enable", "BOOL", "启动", ""],
        ["OUT", "Done", "BOOL", "完成", ""],
    ]


def test_st_text_for_export_returns_program_source() -> None:
    program = ProgramUnit(
        uid="main-1",
        name="主程序 1",
        implementation_language="st",
        st_document=StDocument(source="IF Enable THEN\n    Done := TRUE;\nEND_IF;"),
    )

    assert st_text_for_export(program) == "IF Enable THEN\n    Done := TRUE;\nEND_IF;"


def test_cxr_text_from_ladder_networks_is_stable() -> None:
    text = cxr_text_from_ladder_networks(
        "主程序 1",
        [
            LadderNetwork(
                title="启动保持",
                rows=4,
                columns=6,
                comment="主回路",
                cells=[
                    LadderCell(1, 1, LadderElement(kind="contact_no", operand="StartPB")),
                    LadderCell(1, 4, LadderElement(kind="coil", operand="MotorRun")),
                ],
            )
        ],
    )

    assert text == (
        "; CXR reusable ladder generated by omron-io-planner\n"
        "PROGRAM\t主程序 1\n"
        "NETWORK\t1\t启动保持\t主回路\t4\t6\n"
        "CELL\t1\t1\tcontact_no\tStartPB\t\t\n"
        "CELL\t1\t4\tcoil\tMotorRun\t\t\n"
        "END_NETWORK\n"
        "END_PROGRAM\n"
    )
