# -*- coding: utf-8 -*-
"""CXR 梯形图文本发射（单点收口，供 program_export 等调用）。"""
from __future__ import annotations

from .program_models import LadderCell, LadderInstructionInstance, LadderNetwork


def cxr_program_header_lines(program_name: str) -> list[str]:
    return [
        "; CXR reusable ladder generated by omron-io-planner",
        f"PROGRAM\t{program_name}",
    ]


def cxr_format_version_v2_line() -> str:
    return "FORMAT_VERSION\t2"


def cxr_network_header_v2(network_index: int, network: LadderNetwork) -> str:
    return (
        f"NETWORK\t{network_index}\t{network.title}\t{network.comment}\t"
        f"{len(network.rungs)}\t{network.columns}"
    )


def cxr_cell_line_v2(rung_index: int, inst: LadderInstructionInstance) -> str:
    op0 = inst.operands[0] if inst.operands else ""
    extra = inst.operands[1:] if len(inst.operands) > 1 else []
    params = ",".join(extra)
    return f"CELL\t{rung_index}\t{inst.slot_index}\t{inst.spec_id}\t{op0}\t{params}\t{inst.comment}"


def cxr_network_header_v1(network_index: int, network: LadderNetwork) -> str:
    return (
        f"NETWORK\t{network_index}\t{network.title}\t{network.comment}\t"
        f"{network.rows}\t{network.columns}"
    )


def cxr_cell_line_v1(cell: LadderCell) -> str | None:
    element = cell.element
    if element is None:
        return None
    params = ",".join(element.params)
    return f"CELL\t{cell.row}\t{cell.column}\t{element.kind}\t{element.operand}\t{params}\t{element.comment}"


def cxr_lines_from_ladder_networks(program_name: str, networks: list[LadderNetwork]) -> list[str]:
    lines = cxr_program_header_lines(program_name)
    any_v2 = any(getattr(n, "format_version", 1) >= 2 and n.rungs for n in networks)
    if any_v2:
        lines.append(cxr_format_version_v2_line())
    for index, network in enumerate(networks, start=1):
        if getattr(network, "format_version", 1) >= 2 and network.rungs:
            lines.append(cxr_network_header_v2(index, network))
            for r_i, rung in enumerate(network.rungs):
                ordered = sorted(rung.elements, key=lambda e: (e.slot_index, e.spec_id))
                for inst in ordered:
                    lines.append(cxr_cell_line_v2(r_i, inst))
        else:
            lines.append(cxr_network_header_v1(index, network))
            for cell in sorted(network.cells, key=lambda current: (current.row, current.column)):
                row = cxr_cell_line_v1(cell)
                if row is not None:
                    lines.append(row)
        lines.append("END_NETWORK")
    lines.append("END_PROGRAM")
    return lines


def cxr_text_from_ladder_networks(program_name: str, networks: list[LadderNetwork]) -> str:
    return "\n".join(cxr_lines_from_ladder_networks(program_name, networks)) + "\n"
