# -*- coding: utf-8 -*-
"""程序域导出。"""
from __future__ import annotations

from .program_models import LadderNetwork, ProgramUnit, VariableDecl


def rows_variable_table(variables: list[VariableDecl]) -> list[list[str]]:
    rows = [["类别", "名称", "数据类型", "注释", "初始值"]]
    for variable in variables:
        rows.append(
            [
                variable.category,
                variable.name,
                variable.data_type,
                variable.comment,
                variable.initial_value,
            ]
        )
    return rows


def st_text_for_export(program: ProgramUnit) -> str:
    return program.st_document.source


def cxr_text_from_ladder_networks(program_name: str, networks: list[LadderNetwork]) -> str:
    lines = [
        "; CXR reusable ladder generated by omron-io-planner",
        f"PROGRAM\t{program_name}",
    ]
    for index, network in enumerate(networks, start=1):
        lines.append(
            f"NETWORK\t{index}\t{network.title}\t{network.comment}\t{network.rows}\t{network.columns}"
        )
        for cell in sorted(network.cells, key=lambda current: (current.row, current.column)):
            element = cell.element
            if element is None:
                continue
            params = ",".join(element.params)
            lines.append(
                f"CELL\t{cell.row}\t{cell.column}\t{element.kind}\t{element.operand}\t{params}\t{element.comment}"
            )
        lines.append("END_NETWORK")
    lines.append("END_PROGRAM")
    return "\n".join(lines) + "\n"
